index:
  name: semantic-router-index
  prefix: "route"
  storage_type: "hash"

fields:
  - name: name
    type: "text"
  - name: vector
    type: "vector"
    attrs:
      algorithm: "FLAT"
      dims: 384 # This MUST match the output dimension of the transformer model
      distance_metric: "COSINE"
      datatype: "FLOAT32"
